### ISSUE TITLE
attacher.call is not a function when used in a solid-start/vinxi project

### ISSUE THREAD

**Issue by arnfaldur** [remark-embedder/core#129]
- `remark-embedder-core` version: 3.0.2
- `node` version: 22.0.0
- `pnpm` version: 9.1.1

Relevant code or config

```js
// file: app.config.ts

import { defineConfig } from "@solidjs/start/config";

import mdx from "@vinxi/plugin-mdx";

import remarkEmbedder from "@remark-embedder/core";
import oembedTransformer from "@remark-embedder/transformer-oembed";

export default defineConfig({
  extensions: ["tsx", "mdx", "md"],
  server: {
    preset: "aws-amplify",
  },
  vite: {
    plugins: [
      mdx.default.withImports({})({
        jsx: true,
        jsxImportSource: "solid-js",
        providerImportSource: "solid-mdx",
        remarkPlugins: [
          [
            remarkEmbedder.default,
            { transformers: [oembedTransformer.default] },
          ],
        ],
        enforce: "pre",
      }),
    ],
  },
});

```

Trying to use this plugin in a SolidStart 1.0 RC project. SolidStart uses vinxi as a build system which provides a wrapper for the vite mdx processor. 

When trying to use the plugin, this error occurs when processing an md/mdx file:

```
  file: src/routes/.../index.md
  at Function.freeze (node_modules/.pnpm/unified@11.0.4/node_modules/unified/lib/index.js:636:36)
  at Function.process (node_modules/.pnpm/unified@11.0.4/node_modules/unified/lib/index.js:716:10)
  at Module.compile (node_modules/.pnpm/@mdx-js+mdx@3.0.1/node_modules/@mdx-js/mdx/lib/compile.js:40:35)
  at transform2 (node_modules/.pnpm/@vinxi+plugin-mdx@3.7.1_@mdx-js+mdx@3.0.1/node_modules/@vinxi/plugin-mdx/dist/index.cjs:1535:30)
  at async Object.transform (node_modules/.pnpm/@vinxi+plugin-mdx@3.7.1_@mdx-js+mdx@3.0.1/node_modules/@vinxi/plugin-mdx/dist/index.cjs:2171:16)
  at async transform (node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:18680:16)
  at async ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:18896:36) 
```

This issue is the same as the one encountered [here](https://github.com/shikijs/twoslash/issues/147) and it has an easy workaround.

Just use `remarkEmbedder.default` instead of `remarkEmbedder` directly, like I do in the config above. The same goes for the Oembed transformer.

I solved this issue with the debugger but wanted to save someone else the trouble by writing about it here. I'm not sure which piece of the stack is responsible for the problem but the workaround is easy so it's no biggie.

**Comment by arnfaldur** [comment]
As I already provided a decent solution and I'm not sure the problem is due to any issue with the code in this repo, I'm just going to close the issue.

If you think that it is an issue with this repo's code, you can of course open it again.
