### ISSUE TITLE
Update dependencies to function with updated Remark/Unified

### ISSUE THREAD

**Issue by mikestecker** [remark-embedder/core#46]
- `remark-embedder-core` version: ^1.4.2
- `node` version: 14.17.6
- `npm` version: 6.14.15

No longer works after upgrading:

`unified`:  ^9.2.2  --> ^10.1.0
`remark-rehype`:  ^8.1.0  --> ^9.1.0
`remark-gfm`:  ^1.0.0  --> ^2.0.0
plus a few others...

my full transformer is:

```
// TODO: @mapbox/rehype-prism does not have typescript definition
// @ts-ignore
import rehypePrism from '@mapbox/rehype-prism';
import remarkEmbedder, { TransformerInfo } from '@remark-embedder/core';
import oembedTransformer from '@remark-embedder/transformer-oembed';
import rehypeExternalLinks from 'rehype-external-links';
import rehypeStringify from 'rehype-stringify';
import remarkGfm from 'remark-gfm';
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import { unified } from 'unified';

type GottenHTML = string | null;

function handleHTML(html: GottenHTML, info: TransformerInfo) {
  const { url, transformer } = info;
  if (transformer.name === '@remark-embedder/transformer-oembed' || url.includes('youtube.com')) {
    return `<div class="embedded-youtube aspect-w-16 aspect-h-9">${html}</div>`;
  }
  return html;
}

export async function markdownToHtml(markdown: string) {
  const result = await unified()
    .use(remarkParse)
    .use(remarkEmbedder, {
      transformers: [oembedTransformer],
      handleHTML,
    })
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeExternalLinks, { target: '_blank' })
    .use(rehypePrism)
    .use(rehypeStringify)
    .process(markdown);
  return result.toString().replace(/@@baseUrl@@/g, process.env.baseUrl || '');
}
```

### What I've tried:

I have attempted to [fork and update the base packages](https://github.com/mikestecker/core/commits/dev-esm), however I'm seeing the following errors with Jest and I don't know how to resolve it:

```
    Details:

    /Volumes/Sandisk SSD/Development/remark-embedder-core/node_modules/remark/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {unified} from 'unified'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import {remark} from 'remark'
        | ^
      2 | import remarkHTML from 'remark-html'
      3 |
      4 | import remarkEmbedder from '../'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1723:14)
      at Object.<anonymous> (src/__tests__/index.ts:1:1)
```

**Comment by MichaelDeBoey** [comment]
The suggested version are all ESM versions.

As jest currently doesn't support ESM (yet), we can't update these dependencies (for now).

**Comment by kentcdodds** [comment]
Just pushed an update for all deps to be on the latest version of everything.
